package com.evony.client.response {
import com.evony.common.server.events.AllianceChatMsg;
import com.evony.common.server.events.BuildComplate;
import com.evony.common.server.events.BuildingQueueUpdate;
import com.evony.common.server.events.CastleBuffUpdate;
import com.evony.common.server.events.CastleFieldUpdate;
import com.evony.common.server.events.CastleUpdate;
import com.evony.common.server.events.CbUpdate;
import com.evony.common.server.events.ChangeName;
import com.evony.common.server.events.ChannelChatMsg;
import com.evony.common.server.events.ConnectionLost;
import com.evony.common.server.events.EnemyArmysUpdate;
import com.evony.common.server.events.FortificationsUpdate;
import com.evony.common.server.events.FriendArmysUpdate;
import com.evony.common.server.events.HeroUpdate;
import com.evony.common.server.events.InjuredTroopUpdate;
import com.evony.common.server.events.ItemBuff;
import com.evony.common.server.events.ItemUpdate;
import com.evony.common.server.events.KickedOut;
import com.evony.common.server.events.LoginResponse;
import com.evony.common.server.events.NewFinishedQuest;
import com.evony.common.server.events.NewMail;
import com.evony.common.server.events.NewReport;
import com.evony.common.server.events.OnlineBonus;
import com.evony.common.server.events.PackageList;
import com.evony.common.server.events.PlayerBuffUpdate;
import com.evony.common.server.events.PlayerInfoUpdate;
import com.evony.common.server.events.PrivateChatMessage;
import com.evony.common.server.events.QuestFinished;
import com.evony.common.server.events.RegisterResponse;
import com.evony.common.server.events.ResearchCompleteUpdate;
import com.evony.common.server.events.ResourceUpdate;
import com.evony.common.server.events.SecurityCodeRemovedEvent;
import com.evony.common.server.events.SelfArmysUpdate;
import com.evony.common.server.events.StrategyBuff;
import com.evony.common.server.events.SystemInfoMsg;
import com.evony.common.server.events.TradesUpdate;
import com.evony.common.server.events.TransingTradeUpdate;
import com.evony.common.server.events.TroopUpdate;
import com.evony.common.server.events.WorldChatMsg;

public class ServerEvents extends Object {
    public static const BUILDING_QUEUE_UPDATE:String = "server.BuildingQueueUpdate";
    public static const BUILD_COMPLATE:String = "server.BuildComplate";
    public static const FORTIFICATIONS_UPDATE:String = "server.FortificationsUpdate";
    public static const TRANSING_TRADE_UPDATE:String = "server.TransingTradeUpdate";
    public static const ALLIANCE_CHAT_MSG:String = "server.AllianceChatMsg";
    public static const ONLINE_BONUS:String = "server.OnlineBonus";
    public static const NEW_MAIL:String = "server.NewMail";
    public static const PACKAGE_LIST:String = "server.PackageList";
    public static const RESOURCE_UPDATE:String = "server.ResourceUpdate";
    public static const CASTLE_BUFF_UPDATE:String = "server.CastleBuffUpdate";
    public static const PLAYER_INFO_UPDATE:String = "server.PlayerInfoUpdate";
    public static const STRATEGY_BUFF:String = "server.StrategyBuff";
    public static const WORLD_CHAT_MSG:String = "server.WorldChatMsg";
    public static const CB_UPDATE:String = "server.CbUpdate";
    public static const HERO_UPDATE:String = "server.HeroUpdate";
    public static const CHANGE_NAME:String = "server.ChangeName";
    public static const INJURED_TROOP_UPDATE:String = "server.InjuredTroopUpdate";
    public static const CASTLE_FIELD_UPDATE:String = "server.CastleFieldUpdate";
    public static const SECURITY_CODE_REMOVED_EVENT:String = "server.SecurityCodeRemovedEvent";
    public static const ENEMY_ARMYS_UPDATE:String = "server.EnemyArmysUpdate";
    public static const QUEST_FINISHED:String = "server.QuestFinished";
    public static const NEW_REPORT:String = "server.NewReport";
    public static const NEW_FINISHED_QUEST:String = "server.NewFinishedQuest";
    public static const CHANNEL_CHAT_MSG:String = "server.ChannelChatMsg";
    public static const PLAYER_BUFF_UPDATE:String = "server.PlayerBuffUpdate";
    public static const FRIEND_ARMYS_UPDATE:String = "server.FriendArmysUpdate";
    public static const KICKED_OUT:String = "server.KickedOut";
    public static const SYSTEM_INFO_MSG:String = "server.SystemInfoMsg";
    public static const PRIVATE_CHAT_MESSAGE:String = "server.PrivateChatMessage";
    public static const REGISTER_RESPONSE:String = "server.RegisterResponse";
    public static const SELF_ARMYS_UPDATE:String = "server.SelfArmysUpdate";
    public static const RESEARCH_COMPLETE_UPDATE:String = "server.ResearchCompleteUpdate";
    public static const CASTLE_UPDATE:String = "server.CastleUpdate";
    public static const ITEM_UPDATE:String = "server.ItemUpdate";
    public static const TROOP_UPDATE:String = "server.TroopUpdate";
    public static const LOGIN_RESPONSE:String = "server.LoginResponse";
    public static const TRADES_UPDATE:String = "server.TradesUpdate";
    public static const CONNECTION_LOST:String = "server.ConnectionLost";
    public static const ITEM_BUFF:String = "server.ItemBuff";
    public static var Map:Object = new Object();

    public function ServerEvents() {
        super();
    }

    Map[STRATEGY_BUFF] = StrategyBuff;
    Map[CHANGE_NAME] = ChangeName;
    Map[RESOURCE_UPDATE] = ResourceUpdate;
    Map[INJURED_TROOP_UPDATE] = InjuredTroopUpdate;
    Map[PLAYER_BUFF_UPDATE] = PlayerBuffUpdate;
    Map[BUILDING_QUEUE_UPDATE] = BuildingQueueUpdate;
    Map[PLAYER_INFO_UPDATE] = PlayerInfoUpdate;
    Map[SELF_ARMYS_UPDATE] = SelfArmysUpdate;
    Map[CHANNEL_CHAT_MSG] = ChannelChatMsg;
    Map[CASTLE_FIELD_UPDATE] = CastleFieldUpdate;
    Map[CONNECTION_LOST] = ConnectionLost;
    Map[WORLD_CHAT_MSG] = WorldChatMsg;
    Map[PACKAGE_LIST] = PackageList;
    Map[TRANSING_TRADE_UPDATE] = TransingTradeUpdate;
    Map[TROOP_UPDATE] = TroopUpdate;
    Map[BUILD_COMPLATE] = BuildComplate;
    Map[TRADES_UPDATE] = TradesUpdate;
    Map[SYSTEM_INFO_MSG] = SystemInfoMsg;
    Map[ALLIANCE_CHAT_MSG] = AllianceChatMsg;
    Map[LOGIN_RESPONSE] = LoginResponse;
    Map[NEW_REPORT] = NewReport;
    Map[HERO_UPDATE] = HeroUpdate;
    Map[FORTIFICATIONS_UPDATE] = FortificationsUpdate;
    Map[ITEM_UPDATE] = ItemUpdate;
    Map[NEW_FINISHED_QUEST] = NewFinishedQuest;
    Map[CASTLE_UPDATE] = CastleUpdate;
    Map[RESEARCH_COMPLETE_UPDATE] = ResearchCompleteUpdate;
    Map[REGISTER_RESPONSE] = RegisterResponse;
    Map[CB_UPDATE] = CbUpdate;
    Map[PRIVATE_CHAT_MESSAGE] = PrivateChatMessage;
    Map[FRIEND_ARMYS_UPDATE] = FriendArmysUpdate;
    Map[CASTLE_BUFF_UPDATE] = CastleBuffUpdate;
    Map[ITEM_BUFF] = ItemBuff;
    Map[SECURITY_CODE_REMOVED_EVENT] = SecurityCodeRemovedEvent;
    Map[QUEST_FINISHED] = QuestFinished;
    Map[NEW_MAIL] = NewMail;
    Map[ENEMY_ARMYS_UPDATE] = EnemyArmysUpdate;
    Map[ONLINE_BONUS] = OnlineBonus;
    Map[KICKED_OUT] = KickedOut;
}
}
